name: Collate Documentation
on:
  schedule:
    - cron:  '42 14 * * *'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  getdocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: |
        cd sandbox
        python update-docs.py
    - env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Commit files
        run: |
          cd sandbox
          git config --local user.email "${{ secrets.USER_EMAIL }}"
          git config --local user.name "${{ secrets.USER_NAME }}"
          git commit -m "Update documentation" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
